### ISSUE TITLE
importing library to native Android app

### ISSUE THREAD

**Issue by ahmetcj4** [PirataFrancis/sunmi-card-reader#3]
Hello,
Thank you very much for wrapper library for card reader on sunmi. I want to use this library on my native Android app but couldn't manage it. Could you please help me resolve this issue.

**Comment by thedevcaptain** [comment]
Hello!!
Actually this is a Cordova Wrapper for the library but if you need help with the Android SDK, just contact me

**Comment by OttoChamo** [comment]
@PirataFrancis Hello I need help with the Android SDK, could you help me?
